services:
  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    ports:
      - "8991:80"
    networks:
      - proxy
      - data-net
    environment:
      - TZ=Europe/Zurich
      - IS_HTTPS_ENABLED=true
      - SHELL_VERBOSITY=3
      - SKIP_INITIAL_GEOLITE_DOWNLOAD=true
      - DEFAULT_DOMAIN=${SHLINK_SERVER_FQDN}
      - DB_DRIVER=mysql
      - DB_NAME=shlink
      - DB_USER=shlink
      - DB_PASSWORD=${SHLINK_DB_PASSWORD}
      - DB_HOST=database
      - INITIAL_API_KEY=${SHLINK_INITIAL_API_KEY}
      - GEOLITE_LICENSE_KEY=${SHLINK_GEOLITE_LICENSE_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy" # is to define which network should be used for traeffik (only needed if multiple networks are linked)
      - "traefik.http.routers.shlink-backend-http.entrypoints=web" # 'web' could be 'http' if also in config file used
      - "traefik.http.routers.shlink-backend-http.rule=Host(`{shlink.fqdn}`)"
      - "traefik.http.middlewares.shlink-backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.shlink-backend-https.middlewares=shlink-backend-https-redirect"
      - "traefik.http.routers.shlink-backend-https.entrypoints=websecure" # 'websecure' could be 'https' if also in config file used
      - "traefik.http.routers.shlink-backend-https.rule=Host(`{shlink.fqdn}`)"
      - "traefik.http.routers.shlink-backend-https.tls=true"
      - "traefik.http.routers.shlink-backend-https.tls.certresolver=infomaniak"

  shlink-web-client:
    hostname: shlink-web-client
    image: shlinkio/shlink-web-client:stable
    restart: unless-stopped
    depends_on:
      - shlink
    ports:
      - 8990:8080
    networks:
      - proxy
    environment:
      - TZ=Europe/Zurich
      - PUID=1000
      - PGID=1000
      - SHLINK_SERVER_URL=${SHLINK_SERVER_URL}
      - SHLINK_SERVER_API_KEY=${SHLINK_INITIAL_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shlink-ui-http.entrypoints=web" # 'web' could be 'http' if also in config file used
      - "traefik.http.routers.shlink-ui-http.rule=Host(`{shlink.fqdn.ui}`)"
      - "traefik.http.middlewares.shlink-ui-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.shlink-ui-https.middlewares=shlink-ui-https-redirect"
      - "traefik.http.routers.shlink-ui-https.entrypoints=websecure" # 'websecure' could be 'https' if also in config file used
      - "traefik.http.routers.shlink-ui-https.rule=Host(`{shlink.fqdn.ui}`)"
      - "traefik.http.routers.shlink-ui-https.tls=true"
      - "traefik.http.routers.shlink-ui-https.tls.certresolver=infomaniak"
      - "traefik.http.middlewares.shlink-ui-https.ipallowlist.sourcerange=${remote.host.ip.or.dyndns}"
      - "traefik.http.middlewares.shlink-ui-http.ipallowlist.sourcerange=${remote.host.ip.or.dyndns}"
      - "traefik.http.routers.shlink-ui-https.middlewares=shlink-ui-https@docker" # important to add the middleware to your router
      - "traefik.http.routers.shlink-ui-http.middlewares=shlink-ui-http@docker" # important to add the middleware to your router
      # no allow-list on account of accessing from IP-adresses which are not from home

networks:
  proxy:
    internal: false
  data-net:
    external: true