services:

  shlink:
    hostname: shlink
    image: shlinkio/shlink:stable
    restart: unless-stopped
    ports:
      - "8991:8080"
    environment:
      TZ: "Europe/Zurich"
      PUID: 1000
      PGID: 1000
      DEFAULT_DOMAIN: '${SHLINK_FQDN}'
      IS_HTTPS_ENABLED: 'false'
      GEOLITE_LICENSE_KEY: '${SHLINK_GEOLITE_LICENSE_KEY}'
      DB_DRIVER: 'mysql'
      DB_NAME: '${SHLINK_DB_NAME}'
      DB_HOST: 'shlink_mysql'
      DB_PORT: '3306'
      DB_USER: '${SHLINK_DB_USER}'
      DB_PASSWORD: '${SHLINK_DB_PASSWORD}'
      MEMORY_LIMIT: '256M'
      INITIAL_API_KEY: '${SHLINK_INITIAL_API_KEY}' # an API key that will be created once during container start-up
    networks:
      - proxy
    depends_on:
        - shlink_mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shlink-backend-http.entrypoints=web" # 'web' could be 'http' if also in config file used
      - "traefik.http.routers.shlink-backend-http.rule=Host(`{shlink.fqdn}`)"
      - "traefik.http.middlewares.shlink-backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.shlink-backend-https.middlewares=shlink-backend-https-redirect"
      - "traefik.http.routers.shlink-backend-https.entrypoints=websecure" # 'websecure' could be 'https' if also in config file used
      - "traefik.http.routers.shlink-backend-https.rule=Host(`{shlink.fqdn}`)"
      - "traefik.http.routers.shlink-backend-https.tls=true"
      - "traefik.http.routers.shlink-backend-https.tls.certresolver=infomaniak"

  shlink-web-client:
    hostname: shlink-web-client
    image: shlinkio/shlink-web-client:stable
    environment:
        TZ: "Europe/Zurich"
        PUID: 1000
        PGID: 1000
        SHLINK_SERVER_URL: "${SHLINK_SERVER_URL}"
        SHLINK_SERVER_API_KEY: "${SHLINK_INITIAL_API_KEY}"
    depends_on:
        - shlink
    ports:
        - 8990:8080
    networks:
        - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shlink-ui-http.entrypoints=web" # 'web' could be 'http' if also in config file used
      - "traefik.http.routers.shlink-ui-http.rule=Host(`{shlink.fqdn.ui}`)"
      - "traefik.http.middlewares.shlink-ui-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.shlink-ui-https.middlewares=shlink-ui-https-redirect"
      - "traefik.http.routers.shlink-ui-https.entrypoints=websecure" # 'websecure' could be 'https' if also in config file used
      - "traefik.http.routers.shlink-ui-https.rule=Host(`{shlink.fqdn.ui}`)"
      - "traefik.http.routers.shlink-ui-https.tls=true"
      - "traefik.http.routers.shlink-ui-https.tls.certresolver=infomaniak"
      # - "traefik.http.middlewares.shlink-ui-https.ipwhitelist.sourcerange=${remote.host.ip.or.dyndns}"
      # - "traefik.http.middlewares.shlink-ui-http.ipwhitelist.sourcerange=${remote.host.ip.or.dyndns}"
      # - "traefik.http.routers.shlink-ui-https.middlewares=shlink-ui-https@docker" # important to add the middleware to your router
      # - "traefik.http.routers.shlink-ui-http.middlewares=shlink-ui-http@docker" # important to add the middleware to your router
      # no allow-list on account of accessing from IP-adresses which are not from home

  shlink_mysql:
    image: mysql:8.0
    container_name: shlink_mysql
    hostname: shlink_mysql
    restart: unless-stopped
    networks:
      - proxy
    ports:
     - '3306:3306'
    environment:
      MYSQL_DATABASE: "${SHLINK_DB_NAME}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: "${SHLINK_DB_USER}"
      MYSQL_PASSWORD: "${SHLINK_DB_PASSWORD}"
    volumes:
      - shlink_db:/var/lib/mysql
    labels:
      - "traefik.enable=false"
      - "docker-volume-backup.stop-during-backup=true"

volumes:
  shlink_db:

networks:
  proxy:
    external: true