---
# roles/services/tasks/main.yml

- name: Clone services from repository
  ansible.builtin.git:
    repo: 'https://github.com/m-mattia-m/infrastructure-setup.git'
    dest: /home/{{ ansible_user }}/infrastructure
    clone: true
    version: ansible

- name: Create docker proxy network
  become: true # run command with sudo access
  ansible.builtin.docker_network:
    name: proxy

- name: Call replacement tasks
  ansible.builtin.include_tasks: ./replace_fqdn/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services/traefik
    placeholder: "{ansible.fqdn}"
    replacement: "{{ fqdn }}"

- name: Start traefik
  become: true # run command with sudo access
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/traefik
