---
# roles/services/tasks/main.yml

- name: Clone services from repository
  ansible.builtin.git:
    repo: 'https://github.com/m-mattia-m/infrastructure-setup.git'
    dest: /home/{{ ansible_user }}/infrastructure
    clone: true
    version: ansible

- name: Update traefik acme.json permissions
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/infrastructure/services/traefik/data/acme.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Create docker proxy network
  become: true # run command with sudo access
  ansible.builtin.docker_network:
    name: proxy

- name: Call 'fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{ansible.fqdn}"
    replacement: "{{ fqdn }}"

- name: Call 'ansible-user' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "${ANSIBLE_USER}"
    replacement: "{{ ansible_user }}"

- name: Call 'shlink-fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{shlink.fqdn}"
    replacement: "l.mattiamueggler.ch"

- name: Call 'shlink-fqdn-ui' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{shlink.fqdn.ui}"
    replacement: "shlink.services.mattiamueggler.ch"

- name: Call 'invoiceplane-fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{invoiceplane.fqdn}"
    replacement: "invoiceplane.services.mattiamueggler.ch"

- name: Call 'portainer-fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{portainer.fqdn}"
    replacement: "{{ fqdn }}"

- name: Call 'caServer' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "${caServer}"
    replacement: "https://acme-staging-v02.api.letsencrypt.org/directory" # For testing
    # replacement: "https://acme-v02.api.letsencrypt.org/directory" # For production

- name: Call 'AllowList - DynDNS' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: "/home/{{ ansible_user }}/infrastructure/services"
    placeholder: "replace:home.dyn.dns"
    replacement: "home.muegglers.com"

- name: Call 'AllowList - files to update' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: "/home/{{ ansible_user }}/infrastructure/services"
    placeholder: "replace.files.to.update"
    replacement: "/home/{{ ansible_user }}/infrastructure/services/whoami/docker-compose.yaml /home/{{ ansible_user }}/infrastructure/services/shlink/docker-compose.yaml /home/{{ ansible_user }}/infrastructure/services/portainer/docker-compose.yaml /home/{{ ansible_user }}/infrastructure/services/invoiceplane/docker-compose.yaml /home/{{ ansible_user }}/infrastructure/services/traefik/docker-compose.yaml"

- name: Create cron-job for dynDNS-check every day at 2am
  ansible.builtin.cron:
    name: "refresh dynDNS"
    minute: "0"
    hour: "2"
    job: "sh /home/{{ ansible_user }}/infrastructure/services/dyndns-check/check-dyndns.sh"

- name: Run "Check-DynDNS" Script
  ansible.builtin.shell: "sh /home/{{ ansible_user }}/infrastructure/services/dyndns-check/check-dyndns.sh"

- name: Kill processes running on port 80
  ansible.builtin.include_tasks: ./kill-process/tasks/main.yaml

- name: Copy environment
  vars:
    parent_dir: "{{ playbook_dir | dirname }}"
  ansible.builtin.copy:
    src: "{{ parent_dir }}/config.env"
    dest: "/home/{{ ansible_user }}/infrastructure/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Generate environment files with }/config.env
  ansible.builtin.make:
    chdir: "/home/{{ ansible_user }}/infrastructure/"
    target: generate-environment

- name: Start traefik
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/traefik

- name: Start whoami
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/whoami

- name: Start portainer
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/portainer

- name: Start shlink
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/shlink

- name: Start invoiceplane
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/invoiceplane

# - name: Pause before start backup to ensure that every database started up successfully
#   ansible.builtin.pause:
#     seconds: 180
#     # minutes: 1

# - name: Start Backup
#   become: true
#   community.docker.docker_compose_v2:
#     project_src: /home/{{ ansible_user }}/infrastructure/services/backup
