---
# roles/services/tasks/main.yml

- name: Clone services from repository
  ansible.builtin.git:
    repo: 'https://github.com/m-mattia-m/infrastructure-setup.git'
    dest: /home/{{ ansible_user }}/infrastructure
    clone: true
    version: ansible

- name: Update traefik acme.json permissions
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/infrastructure/services/traefik/data/acme.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Create docker proxy network
  become: true # run command with sudo access
  community.docker.docker_network:
    name: proxy

- name: S3 File Downloader
  ansible.builtin.include_tasks: ./backup-restore/tasks/main.yaml
  vars:
    s3_bucket: "{{ s3_bucket_name }}"
    destination: "/path/to/destination"
    file_name: ""
    aws_endpoint_url: "{{ s3_endpoint_url }}"
    aws_access_id: "{{ s3_access_id }}"
    aws_secret_key: "{{ s3_access_key }}"
    # restore_backup: false
    # restore_backup_name: ""

- name: Call 'fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{ansible.fqdn}"
    replacement: "{{ fqdn }}"

- name: Call 'ansible-user' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "${ANSIBLE_USER}"
    replacement: "{{ ansible_user }}"

- name: Call 'shlink-fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{shlink.fqdn}"
    replacement: "{{ shlink_server_fqdn }}"

- name: Call 'invoiceplane-fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{invoiceplane.fqdn}"
    replacement: "{{ invoiceplane_fqdn }}"

- name: Call 'portainer-fqdn' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "{portainer.fqdn}"
    replacement: "{{ fqdn }}"

- name: Call 'caServer' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: /home/{{ ansible_user }}/infrastructure/services
    placeholder: "${caServer}"
    replacement: "{{ ca_server }}" # For testing

- name: Call 'AllowList - DynDNS script' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: "/home/{{ ansible_user }}/infrastructure/services"
    placeholder: "replace:home.dyn.dns"
    replacement: "{{ allowed_dyn_dns }}"

- name: Call 'AllowList - files to update' replacement tasks
  ansible.builtin.include_tasks: ./replace/tasks/main.yaml
  vars:
    target_directory: "/home/{{ ansible_user }}/infrastructure/services"
    placeholder: "replace.files.to.update"
    replacement: "{{ allow_list_files_to_update }}"

- name: Create cron-job for dynDNS-check every day at 2am
  ansible.builtin.cron:
    name: "refresh dynDNS"
    minute: "0"
    hour: "2"
    job: "sh /home/{{ ansible_user }}/infrastructure/services/dyndns-check/check-dyndns.sh"

- name: Run "Check-DynDNS" Script
  ansible.builtin.shell: "sh /home/{{ ansible_user }}/infrastructure/services/dyndns-check/check-dyndns.sh"

- name: Kill processes running on port 80
  ansible.builtin.include_tasks: ./kill-process/tasks/main.yaml

- name: Copy environment
  vars:
    parent_dir: "{{ playbook_dir | dirname }}"
  ansible.builtin.copy:
    src: "{{ parent_dir }}/config.env"
    dest: "/home/{{ ansible_user }}/infrastructure/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Generate environment files with }/config.env
  ansible.builtin.make:
    chdir: "/home/{{ ansible_user }}/infrastructure/"
    target: generate-environment

- name: Start DB cluster
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/database-cluster

- name: Create databases 'shlink' and 'invoiceplane'
  community.mysql.mysql_db:
    login_user: root
    login_password: root
    name:
      - shlink
      - invoiceplane
    state: present

- name: Create DB user 'shlink'
  community.mysql.mysql_user:
    login_user: root
    login_password: root
    name: 'shlink'
    password: '{{ shlink_db_password }}'
    priv: '*.*:ALL'
    state: present

- name: Create DB user 'shlink'
  community.mysql.mysql_user:
    name: 'invoiceplane'
    password: '{{ invoiceplane_db_password }}'
    priv: '*.*:ALL'
    state: present

- name: Start traefik
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/traefik

- name: Start whoami
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/whoami

- name: Start portainer
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/portainer

- name: Start invoiceplane
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/invoiceplane

- name: Start shlink
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/shlink

- name: Start Backup
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/backup
