---
- name: Find all files in the target directory
  ansible.builtin.find:
    paths: "{{ target_directory }}"
    recurse: true
    file_type: file
  register: files_to_modify

- name: Replace placeholder with replacement in each file
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: "{{ placeholder | regex_escape }}"
    replace: "{{ item_replacement }}"
  loop: "{{ files_to_modify.files }}"
  loop_control:
    loop_var: item
  when: files_to_modify.matched > 0
  vars:
    item_replacement: "{{ replacement }}"
