---
# roles/initialisation/tasks/main.yml

- name: Ensure the VM is reachable
  ansible.builtin.ping:

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install gnome-terminal and curl via apt
  ansible.builtin.apt:
    name: gnome-terminal, curl
    update_cache: true
  become: true

- name: Install git-all via apt
  ansible.builtin.apt:
    name: git-all
    state: present
    update_cache: true
  become: true

- name: Install make via apt
  ansible.builtin.apt:
    name: make
    state: present
    update_cache: true
  become: true

- name: Copy and execute docker installation script
  become: true
  ansible.builtin.script:
    cmd: "{{ role_path }}/scripts/docker-installation.sh"

- name: Install go via snap
  ansible.builtin.apt:
    name: golang-go
    state: present
  become: true
