- name: Check if port 80 is in use
  become: true
  ansible.builtin.command: "lsof -t -i :80"
  register: port_check
  ignore_errors: true
  changed_when: false

- name: Debug port check result
  ansible.builtin.debug:
    var: port_check.stdout_lines

- name: Kill process if port 80 is in use
  become: true
  ansible.builtin.command: "kill {{ item }}"
  with_items: "{{ port_check.stdout_lines }}"
  when: port_check.stdout_lines is defined and port_check.stdout_lines | length > 0

- name: Debug no process found on port 80
  ansible.builtin.debug:
    msg: "No processes found listening on port 80"
  when: not (port_check.stdout_lines is defined and port_check.stdout_lines | length > 0)
