---

## This part below is NOT testet but should work fine

- name: Read file content
  ansible.builtin.slurp:
    src: open-vpn-access-server-log.txt
  register: file_content

- name: Extract content between markers
  ansible.builtin.set_fact:
    filtered_lines: >-
      {% set start_marker = '+++++++++++++++++++++++++++++++++++++++++++++++' %}
      {% set end_marker = '+++++++++++++++++++++++++++++++++++++++++++++++' %}

      {% set start_index = file_content.content | b64decode | string | regex_search(start_marker + '(.*)' + end_marker) %}
      {% if start_index %}
      {{ start_index.group(1).strip() }}
      {% else %}
      Content between markers not found!
      {% endif %}

- name: Debug output
  ansible.builtin.debug:
    msg: "{{ filtered_lines.stdout }}"


## This part below works fine but `sed ...` should not be used.
#
# - name: Read and filter lines from log file
#   become: true
#   ansible.builtin.command: |
#     sed -n '/+++++++++++++++++++++++++++++++++++++++++++++++/,/+++++++++++++++++++++++++++++++++++++++++++++++/p' open-vpn-access-server-log.txt
#   # ansible.builtin.command: "sed -n '/\(+\)\{20\}/,/\(+\)\{20\}/p' open-vpn-access-server-log.txt"
#   register: filtered_lines

# - name: Debug output
#   ansible.builtin.debug:
#     msg: "{{ filtered_lines.stdout }}"
