---

- name: Run the pre setup tasks
  ansible.builtin.include_role:
    name: pre_setup_tasks

- name: Copy the whole service directory to the remote
  become: true
  ansible.builtin.copy:
    src: ../../../../services/portainer/
    dest: "/home/{{ ansible_user }}/infrastructure/services/portainer/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0744'
    directory_mode: '0744'

- name: Create .env file for Portainer
  become: true
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/infrastructure/services/portainer/.env"
    content: |
      PORTAINER_BASE_URL={{ portainer_base_url }}
      ANSIBLE_HOST_FQDN={{ fqdn }}
      SOURCE_RANGE={{ source_range }}
    mode: '0744'

- name: Start portainer
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/infrastructure/services/portainer
