services:
  backup:
    image: jareware/docker-volume-backup
    networks:
      - proxy
      - database-cluster_internal
    environment:
      AWS_EXTRA_ARGS: "--endpoint-url ${BACKUP_S3_HOST}"
      AWS_DEFAULT_REGION: "${BACKUP_S3_REGION}"
      AWS_S3_BUCKET_NAME: "${BACKUP_S3_BUCKET_NAME}"
      AWS_ACCESS_KEY_ID: "${BACKUP_S3_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${BACKUP_S3_ACCESS_KEY}"
      BACKUP_CRON_EXPRESSION: "0 4 * * *" # "0 4 * * *" # "* * * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allow use of the "stop-during-backup" feature
      - database-compose_database:/backup/shlink_db:ro
    labels:
      - "traefik.enable=false"

volumes:
  database-compose_database:
    external: true

networks:
  proxy:
    external: true
  database-cluster_internal:
    external: true