services:
  backup:
    image: docker-volume-backup-mm:1 # jareware/docker-volume-backup
    environment:
      AWS_EXTRA_ARGS: "--endpoint-url ${BACKUP_S3_HOST}"
      AWS_S3_BUCKET_NAME: "${BACKUP_S3_BUCKET_NAME}"
      AWS_ACCESS_KEY_ID: "${BACKUP_S3_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${BACKUP_S3_ACCESS_KEY}"
    volumes:
      - shlink_db:/backup/shlink_db:ro
      - invoiceplane_db:/backup/invoiceplane_db:ro
      - openvpn:/backup/openvpn:ro
      - portainer_data:/backup/portainer_data:ro

volumes:
  shlink_db:
    external: true
  invoiceplane_db:
    external: true
  openvpn:
    external: true
  portainer_data:
    external: true
