services:
  backup:
    image: jareware/docker-volume-backup
    environment:
      AWS_EXTRA_ARGS: "--endpoint-url ${BACKUP_S3_HOST}"
      AWS_DEFAULT_REGION: "${BACKUP_S3_REGION}"
      AWS_S3_BUCKET_NAME: "${BACKUP_S3_BUCKET_NAME}"
      AWS_ACCESS_KEY_ID: "${BACKUP_S3_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${BACKUP_S3_ACCESS_KEY}"
    volumes:
      - shlink_shlink_db:/backup/shlink_db:ro
      - invoiceplane_invoiceplane_db:/backup/invoiceplane_db:ro
      - portainer_portainer_data:/backup/portainer_data:ro
    labels:
      - "traefik.enable=false"
    networks:
      - proxy

volumes:
  shlink_shlink_db:
    external: true
  invoiceplane_invoiceplane_db:
    external: true
  portainer_portainer_data:
    external: true

networks:
  proxy:
    external: true