services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.20.3
    command: [ '--tlsskipverify' ]
    hostname: portainer
    container_name: portainer
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${PORTAINER_BASE_URL}
      VIRTUAL_PORT: 9000 # 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      # WEB
      - "9443:9443" # "9443:9443"
      # WEB (Insecure) - don't open per default
      # - "9000:9000"
      # EDGE AGENT
      - "8000:8000"
    networks:
      - proxy
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer-http.entrypoints=web" # 'web' could be 'http' if also in config file used
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.${ANSIBLE_HOST_FQDN}`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.portainer-https.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-https.entrypoints=websecure" # 'websecure' could be 'https' if also in config file used
      - "traefik.http.routers.portainer-https.rule=Host(`portainer.${ANSIBLE_HOST_FQDN}`)"
      # - "traefik.http.routers.portainer-https.middlewares=traefik-auth"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.tls.certresolver=infomaniak"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.portainer-https.ipallowlist.sourcerange=${SOURCE_RANGE}"
      - "traefik.http.middlewares.portainer-http.ipallowlist.sourcerange=${SOURCE_RANGE}"
      - "traefik.http.routers.portainer-https.middlewares=portainer-https@docker" # important to add the middleware to your router
      - "traefik.http.routers.portainer-http.middlewares=portainer-http@docker" # important to add the middleware to your router


volumes:
  portainer_data: {}

networks:
  proxy:
    external: true
    internal: false
