version: "3.8"

services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    command: [ '--tlsskipverify' ]
    environment:
      VIRTUAL_HOST: ${BASE_URL}
      VIRTUAL_PORT: 9000 # 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      # WEB
      - "9443:9443" # "9443:9443"
      # WEB (Insecure) - don't open per default
      # - "9000:9000"
      # EDGE AGENT
      - "8000:8000"
    networks:
      - caddy
      - public
    labels:
      caddy: ${BASE_URL}
      caddy.reverse_proxy: "{{upstreams 9000}}"
    hostname: portainer
    container_name: portainer
    restart: always

volumes:
  portainer-data: {}

networks:
  public:
    internal: false
  caddy:
    external: true

