---

- name: Run script
  become: true
  ansible.builtin.script: "{{ script_path }}"
  register: command_output

- name: Save Logs in file
  become: true
  ansible.builtin.copy:
    dest: "{{ target_directory }}"
    content: "{{ command_output.stdout }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: command_output.stdout is defined
