services:

  invoiceplane:
    hostname: invoiceplane
    image: mhzawadi/invoiceplane:1.6.0
    restart: unless-stopped
    environment:
        TZ: "Europe/Zurich"
        MYSQL_HOST: "invoiceplane_mysql"
        MYSQL_USER: "${INVOICEPLANE_DB_USER}"
        MYSQL_PASSWORD: "${INVOICEPLANE_DB_PASSWORD}"
        MYSQL_DB: "${INVOICEPLANE_DB_NAME}"
        MYSQL_PORT: 3307
        IP_URL: "${INVOICEPLANE_HOST}"
        DISABLE_SETUP: false
    depends_on:
        - invoiceplane_mysql
    ports:
        - 8992:80
    networks:
        - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoiceplane-http.entrypoints=web" # 'web' could be 'http' if also in config file used
      - "traefik.http.routers.invoiceplane-http.rule=Host(`{invoiceplane.fqdn}`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.invoiceplane-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.invoiceplane-https.middlewares=invoiceplane-https-redirect"
      - "traefik.http.routers.invoiceplane-https.entrypoints=websecure" # 'websecure' could be 'https' if also in config file used
      - "traefik.http.routers.invoiceplane-https.rule=Host(`{invoiceplane.fqdn}`)"
      # - "traefik.http.routers.invoiceplane-https.middlewares=traefik-auth"
      - "traefik.http.routers.invoiceplane-https.tls=true"
      - "traefik.http.routers.invoiceplane-https.tls.certresolver=infomaniak"
      - "traefik.http.middlewares.invoiceplane-http.ipwhitelist.sourcerange=${remote.host.ip}"
      - "traefik.http.middlewares.invoiceplane-https.ipwhitelist.sourcerange=${remote.host.ip}"

  invoiceplane_mysql:
    image: mysql:8.0
    container_name: invoiceplane_mysql
    hostname: invoiceplane_mysql
    restart: unless-stopped
    networks:
      - proxy
    ports:
     - '3307:3306'
    environment:
      MYSQL_DATABASE: "${INVOICEPLANE_DB_NAME}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: "${INVOICEPLANE_DB_USER}"
      MYSQL_PASSWORD: "${INVOICEPLANE_DB_PASSWORD}"
    volumes:
      - invoiceplane_db:/var/lib/mysql
    labels:
      - "traefik.enable=false"
      - "docker-volume-backup.stop-during-backup=true"

volumes:
  invoiceplane_db:

networks:
  proxy:
    external: true